onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - es5-ext
  - gatsby
  - gatsby-cli
  - lmdb
  - msgpackr-extract
  - sharp
supportedArchitectures:
  os: [darwin, current]
  cpu: [x64, arm64, arm64v8]
